import './globals.css'

import type { Metadata } from 'next'
import { ReactNode } from 'react'
import { project } from '@/app/config/globals'

export const metadata: Metadata = {
  title: `소개 | ${project.companyName.en}`,
  description: 'Generated by UDIT',
}

interface RootLayoutProps {
  children: ReactNode
}

export default function RootLayout({ children }: Readonly<RootLayoutProps>) {
  return (
    <html>
      <body className={''}>
        {/* <Providers> */}
        {children}
        {/* <Portals /> */}
        {/* </Providers> */}
      </body>
    </html>
  )
}
