import type { Metadata } from 'next'
import { ReactNode } from 'react'
import { project } from '@/app/config/globals'

export const metadata: Metadata = {
  title: `소개 | ${project.companyName.en}`,
  description: 'Generated by UDIT',
}

interface IntroLayoutProps {
  children: ReactNode
}

export default function IntroLayout({ children }: Readonly<IntroLayoutProps>) {
  return <div className={''}>{children}</div>
}
